services:
  web:
    build: #compilar la imagen a partir del DockerFile
      context: ..  #raiz del proyecto portfolio
      dockerfile: deploy/DockerFile
      container_name: ctportfolio
    ports:
      - "8010:80"
