#partimos de una imagen base de ubuntu
FROM ubuntu
RUN apt update && apt install -yq --no-install-recommends \
     apache2 \
     nano \
     curl \
     net-tools iputils-ping
RUN useradd -rm -d /home/youssef -s /bin/bash youssef
RUN echo "youssef:1234" | chpasswd
EXPOSE 80
CMD apachectl -D FOREGROUND